// Player
export const PLAYER_CREATED = 'PLAYER_CREATED';
export const PLAYER_DELETED = 'PLAYER_DELETED';
export const DROP_PLAYER = 'DROP_PLAYER';
export const ADD_NEW_PLAYER = 'ADD_NEW_PLAYER';
export const ADD_EXISTING_PLAYER = 'ADD_EXISTING_PLAYER';