// Player
export const PLAYER_CREATED = 'PLAYER_CREATED';
export const PLAYER_DELETED = 'PLAYER_DELETED';
export const DROP_PLAYER = 'DROP_PLAYER';
export const ADD_NEW_PLAYER = 'ADD_NEW_PLAYER';
export const ADD_EXISTING_PLAYER = 'ADD_EXISTING_PLAYER';
export const CREATE_INITIAL_ORDER_LIST = 'CREATE_INITIAL_ORDER_LIST';
export const SEND_PLAYER_ORDER_LIST = 'UPDATE_PLAYER_ORDER_LIST';
export const PLAYER_NAME_UPDATED = 'PLAYER_NAME_UPDATED';